apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: web-app
  namespace: argocd
spec:
  project: default
  
  source:
    repoURL: https://github.com/ne-rustore/infra
    targetRevision: HEAD
    path: .
    directory:
      recurse: true
      include: "k8s/overlays/production/*.yaml"
    
  destination:
    server: https://kubernetes.default.svc
    namespace: web
  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
